# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: antonio.feregrino@gmail.com
author_name: Antonio Feregrino
has_binder: false
has_settings: true
kind: server
labextension_name: presentpy_jupyter
project_short_description: A JupyterLab extension.
python_name: presentpy_jupyter
repository: ''
test: false

