name: Release

env:
  PIP_VERSION: "23.0.0"
  PYTHON_VERSION: "3.10"

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:

  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      with:
        python_version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: python -m pip install -r dev-requirements.txt
  
    - name: Lint the extension
      run: |
        set -eux
        jlpm
        jlpm run lint:check

    - name: Build the extension
      run: |
        set -eux
        python -m pip install .[test]
        jupyter server extension list
        jupyter server extension list 2>&1 | grep -ie "presentpy_jupyter.*OK"
        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "presentpy_jupyter.*OK"
        python -m jupyterlab.browser_check

    - name: Package the extension
      run: |
        set -eux
        pip install build
        python -m build
        pip uninstall -y "presentpy_jupyter" jupyterlab

    - name: Upload extension packages
      uses: actions/upload-artifact@v4
      with:
          name: extension-artifacts
          path: dist/presentpy_jupyter*
          if-no-files-found: error

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      run: python -m twine upload --repository pypi dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
