name: Release

env:
  PIP_VERSION: "23.0.0"
  PYTHON_VERSION: "3.10"

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:

  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      with:
        python_version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install -r dev-requirements.txt

    - name: Build
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: dist

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      run: python -m twine upload --repository pypi dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
